### ISSUE TITLE
[question] how does it work

### ISSUE THREAD

**Issue by adamrzanek** [philscott-dev/homebridge-stagg-ekg-plus#1]
Hi. I’m think of buying this kettle but i want to know how your plugin works? Is it switch or fake thermostat? Can you provide the screenshot? Thanks

**Comment by philscott-dev** [comment]
Yep. Thermostat with heat-only implemented. You use the orange button as a switch. It requires you run https://github.com/philscott-dev/homebridge-stagg-ekg-plus-server on a Pi Zero W near your kettle. 

![IMG_1024](https://user-images.githubusercontent.com/58516501/97496402-423f2280-193f-11eb-9a0f-9e5ddc44cb56.jpeg)
